CREATE TABLE Items (
    id CHAR(36) NOT NULL UNIQUE,
    list_id CHAR(36) NOT NULL,
    content CHAR(250),
    `rank` INT UNSIGNED,
    complete ENUM ('n', 'y') NOT NULL DEFAULT 'n',
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE NOW(),
    PRIMARY KEY(id),
    FOREIGN KEY (list_id) REFERENCES Lists(id) ON UPDATE CASCADE ON DELETE CASCADE
);