CREATE TABLE Lists (
    id CHAR(36) NOT NULL UNIQUE,
    user_id CHAR(36) NOT NULL,
    name CHAR(100),
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES Users(id) ON UPDATE CASCADE ON DELETE CASCADE
);