CREATE TABLE Users (
    id CHAR(36) NOT NULL UNIQUE,
    email CHAR(250) NOT NULL UNIQUE,
    password CHAR(250) NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);